version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /home/davi/mongodb/database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  api:
    image: api/pauta
    restart: always
    build: .
    working_dir: /var/www/pauta
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    depends_on:
      - mongodb

